post https://ucam-it.herokuapp.com/student
Content-Type: application/json

{
"userId" : "16255014",
     "name":"Ahsan Habib Lipon",
     "password" : "lipon2016",
     "dept" : "CSE",
     "phone":"015",
     "mail":"lipon@gmail.com"
}



###
DELETE   http://localhost:3000/student/removecourse/16255010
Content-Type: application/json

{
      "course":["5f8a6700b110c2143c8256e9"]
}
###
PATCH  https://ucam-it.herokuapp.com/coursenotice/5f87c923f3c5880017b4b30e
Content-Type: application/json

{
      "noticeDetails" : "let's see"
}

###
Delete https://ucam-it.herokuapp.com/student/16255008

###
Get  http://localhost:3000/faculty
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlzaHRpYXEuaXFiYWxAaG90bWFpbC5jb20iLCJ1c2VySWQiOiJNSUkiLCJpYXQiOjE2MTMxMzY1OTIsImV4cCI6MTYxMzE0MDE5Mn0.QOFp_VQOqL36jS7cOPyv2ekqtisSQ9RM8U4qFSA9Ktg

###
POST  http://localhost:3000/faculty/auth/login
Content-Type: application/json

{
      "facultyId":"MII",
      "facultyPassword":"MIIuits"
}

###
GET http://localhost:3000/course/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlzaHRpYXEuaXFiYWxAaG90bWFpbC5jb20iLCJ1c2VySWQiOiJNSUkiLCJpYXQiOjE2MTMxMzY1OTIsImV4cCI6MTYxMzE0MDE5Mn0.QOFp_VQOqL36jS7cOPyv2ekqtisSQ9RM8U4qFSA9Ktg


###
DELETE http://localhost:3000/library/5f962ff39fed0b24c89eff93


###
POST http://localhost:3000/student
Content-Type: application/x-www-form-urlencoded
